### ISSUE TITLE
Getting ##[error] when downloading action repository (GithubActions) 

### ISSUE THREAD

**Issue by karl18** [burtonr/octopus-release-action#1]
Hi, 
I'm always getting this error below once using release-action in github:
'burtonr/octopus-action-client@0.1' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.

So getting the same as well either using:
- name: OctopusDeploy Create Release
      uses: burtonr/octopus-action-client@v0.1
or
- name: OctopusDeploy Create Release
      uses: burtonr/octopus-action-client@master

Thx

**Comment by burtonr** [comment]
Good catch! Thank you. I've updated the reference and pushed the new release: https://github.com/burtonr/octopus-release-action/releases/tag/0.2

**Comment by karl18** [comment]
Hi Burton,
Thank you for your message and fixing the bug. But unfortunately I believe I'm still getting Docker pulling errors 'Docker login' failed, seems that public access is not enabled!
 
Pull down action image 'burtonr/octopus-action-client:0.1'
/usr/bin/docker pull burtonr/octopus-action-client:0.1
Error response from daemon: pull access denied for burtonr/octopus-action-client, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

##[warning]Docker pull failed with exit code 1, back off 4.03 seconds before retry.
/usr/bin/docker pull burtonr/octopus-action-client:0.1
Error response from daemon: pull access denied for burtonr/octopus-action-client, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

##[warning]Docker pull failed with exit code 1, back off 2.146 seconds before retry.
/usr/bin/docker pull burtonr/octopus-action-client:0.1
Error response from daemon: pull access denied for burtonr/octopus-action-client, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

##[error]Docker pull failed with exit code 1

Thx a lot appreciate ur support :)

**Comment by burtonr** [comment]
I've pushed the image to the public Docker Hub, so it should be available. 

I'll need to run through this again in it's current state to know that it's ok. I had it working locally/private but apparently had forgot some steps when I decided to make it public. 

I appreciate your patience. Please do let me know if anything else doesn't work as expected. I'll be sure to double check everything this weekend

**Comment by burtonr** [comment]
Hi @karl18! Again, thank you for your patience. 

I've spent the weekend fixing and updating this action, and now have it fully functional. Please upgrade to the latest version and let me know if you have any other issues, or questions. Thanks!

```
uses: burtonr/octopus-release-action@0.5
```
