### ISSUE TITLE
is it possible to pack/push a package using this?

### ISSUE THREAD

**Issue by ericsampson** [burtonr/octopus-release-action#3]
I'm sorry if this is the dumbest question ever, but is it possible to do an Octo pack and push using this Action, or does it only useful to create a release?
Is there another action available that can do octo pack and publish? On the Octopus Deploy blog they are using the octo CLI in a workflow, which is kinda ugly.

Thanks in advance!

**Comment by burtonr** [comment]
Hi there! There are no dumb questions! 

This specific Action is intended to _only_ create an OctopusDeploy release. 

I have plans to also create a "Deploy" Action, however, currently no plans for a "Pack" or "Push" Action.
These Actions use the base OctopusDeploy client: https://github.com/burtonr/octopus-action-client

This is all just to hide away the "kinda ugly" CLI by using the OctopusDeploy SDK.

I'd be happy to accept a PR for adding the pack and push commands so that those additional actions could be created. 
There would probably need to be more work for a "safer" way to handle the additional parameters though.

Or, if you don't mind the wait, I could add it to my personal "to do" list.
Although I couldn't say when it would be completed, I would expect it at least by the end of the month (the holiday break would give me the time to finish it all up).

**Comment by ericsampson** [comment]
Ok cool! I'll keep an eye on things and see if I have any time to look at it over Christmas. 

I'm currently using the CLI to do the pack and push, but it's definitely clunky!!

**Comment by burtonr** [comment]
Hey @ericsampson! Just checking in again.

I started working on adding a `pack` and `push` commands to the original [octopus-action-client](https://github.com/burtonr/octopus-action-client) on the `feature/upgrades` branch.

After some research and playing around a bit, I don't think either of those commands really fit in with the OctopusDeploy Client. `push` _could_ work, but it's limited to the built-in repository. I still plan to finish that up as it may prove useful.

The `pack` command on the other hand, is not a part of the Client features. In this case, what I've done is to build out a GitHub Action that encapsulates the OctopusDeploy CLI here: https://github.com/burtonr/octopous-cli-action Hopefully, it's at least _a little_ easier to use than the CLI directly.

I've only just started work on it, but wanted to let you know to see if that may help you with what you were looking for. It's simple in that it's just a wrapper for calling the CLI. I haven't tested it in the Actions environment yet, but plan to soon. In theory, everything should work as expected, but there are always surprises in the CI/CD world!

Let me know what you think. I could likely get it all tested and ready to go this weekend.

**Comment by ericsampson** [comment]
That sounds awesome 😎 

Would it make sense for it to set whichever of these following inputs are passed in as Env Vars, so that subsequent uses of this Action in the workflow wouldn’t need to pass them in again? 
Because I plan to call the workflow in multiple steps (create release, then pack, then publish). If so, might make sense for the server url to be optional to handle this situation 

> The server URL, API key, username and password can be set as the environment variables OCTOPUS_CLI_SERVER, OCTOPUS_CLI_API_KEY, OCTOPUS_CLI_USERNAME and OCTOPUS_CLI_PASSWORD

**Comment by burtonr** [comment]
Looks to be ready and working now. Didn't catch it earlier, but I _had_ misspelled "octopus" in the repo name! I've fixed it, and all is good now.

Have a look at my testing repo to see a couple of functioning options for using the CLI Action: https://github.com/burtonr/testing/actions/runs/459854132

I took your advice and made sure that everything works well with the official environment variables as well (and updated that readme). 

If you agree, I believe we can close this issue as resolved. If you have any other troubles, you can open an issue on the CLI Action.

**Comment by ericsampson** [comment]
Awesome! I have one question - when using the new action multiple times in a workflow, does it pull the docker image repeatedly?

**Comment by burtonr** [comment]
I believe the short answer is "yes", but it depends on how GitHub Actions is handling it behind the scenes. They are likely just using a local cache and starting a new container instance of the image in the `uses:` block. 

Typically, in the CI/CD world, you want fresh, clean environments for each step. I don't know the answer with certainty, but that's what I guess is happening.

**Comment by ericsampson** [comment]
Thanks, I'm just curious if they do that caching locally, or just pulling it from the container repo each time.

We can close this issue now, thanks a ton for creating the other repo!!
